spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_db?allowMultiQueries=true # allowMultiQueries作用为1.可以在sql语句后携带分号，实现多语句执行。2.可以执行批处理，同时发出多个SQL语句。
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

debug: true